# Generated by Django 3.2 on 2022-04-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='origin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='recent',
            field=models.TextField(blank=True),
        ),
    ]
