# Generated by Django 3.2 on 2022-04-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_origin_place_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='org',
            new_name='Org',
        ),
    ]
